version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
   build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
         command: bundle exec fastlane assemble_build
      - store_artifacts:
         path: app/build/outputs/apk/dev/debug
   test:
    executor: android/android
    steps:
      - checkout
      - run:
         name: Bundle Install
         command: bundle check || bundle install
      - run:
         name: unit tests
         command: bundle exec fastlane test
   test_instrumentation:
     executor: android/android
     steps:
       - checkout
       - run:
          name: Bundle Install
          command: bundle check || bundle install
       - run:
           name: Uninstall crcmod
           command: echo "y" | sudo pip uninstall crcmod
       - run:
           name: Install crcmod
           command: sudo pip install -U crcmod
       - run:
           name: Run instrumentation tests in Firebase Test Lab
           command: bundle exec fastlane instrumentation_tests_testlab
       - store_artifacts:
           path: firebase/
           destination: /firebase/

workflows:
  build_and_test:
    jobs:
      - build
      - test
      - test_instrumentation