version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - run:
         command: bundle exec fastlane assemble_build
     - run:
        name: unit tests
        command: bundle exec fastlane tests
      