version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
   build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
         command: bundle exec fastlane assemble_build
      - store_artifacts:
         path: app/build/outputs/apk/dev/debug
   test:
    executor: android/android
    steps:
      - checkout
      - run:
         name: Bundle Install
         command: bundle check || bundle install
      - run:
         name: unit tests
         command: bundle exec fastlane test

workflows:
  build_and_test:
    jobs:
      - build
      - test