version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - *restore_gradle_cache
     - *restore_gems_cache
     - *android_dependencies
     - *ruby_dependencies
     - *save_gradle_cache
     - *save_gems_cache
     - run:
         command: bundle exec fastlane assemble_build
     - run:
        name: unit tests
        command: bundle exec fastlane tests
      