version: 2

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m

jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle add fastlane --version 2.160.0
      - run:
          name: Install bundle
          command: bundle install
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: "Setting telegram credentials"
          command: bundle exec fastlane set_telegram_creds token:$TELEGRAM_TOKEN chat_id:$TELEGRAM_CHAT_ID
      - run:
          name: Run Build
          command: bundle exec fastlane assemble_build
    
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Run the unit tests
          command: bundle exec fastlane test
      - store_artifacts:
          path: app/build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }} 

  firebase-send:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle add fastlane --version 2.160.0
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: "Install Firebase CLI"
          command: curl -sL firebase.tools | bash
      - run:
          name: Run Build
          command: bundle exec fastlane assemble_build
      - run:
          name: Run the firebase distribution
          command: bundle exec fastlane distribute_firebase token:$FIREBASE_TOKEN
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }} 
  
  instrumentation-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Store service account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: 
          name: Authorize to gcloud
          command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json --project=${GOOGLE_PROJECT_ID}
      - run:
          name: Chmod permissions 
          command: sudo chmod +x "run_firebase_tests.sh"
      - run:
          name: Run the instrumentation tests in Firebase test lab
          command: bundle exec fastlane assemble_with_instrument_tests
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }} 

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - unit-tests
      - instrumentation-tests
      - firebase-send:
          requires:
            - build