# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "assemble_build"
  lane :assemble_build do
    gradle(task: "assembleDebug")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Run instrumentation tests"
  lane :instrumentation_tests do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end 


  desc "Run instrumentation tests in Firebase Test Lab"
  lane :instrumentation_tests_testlab do
    run_tests_firebase_testlab(
      project_id: "roomsample-51434",
      devices: [
        {
          model: "Nexus6P",
          version: "27"
        }
      ],
      delete_firebase_files: true)
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do 
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble_with_instrument_tests do 
    assemble_build
    assemble_test_application
    sh("../ci/run_firebase_tests.sh")
  end

end
